### ISSUE TITLE
Separate attributes and generator assemblies

### ISSUE THREAD

**Issue by hwoodiwiss** [neil-gilbert/Tagify#1]
Firstly, this is a great looking library and a nice use of source generators.

Currently the output assembly that's referenced by downstream projects contains both the attributes _and_ the generator code, which adds a small amount of size to the total project output.

To solve this the generator code can be separated into a separate project (I've used .Generator in the projects I've done this for), and that project referenced _only_ as an analyzer, there's a useful library for that [ViHo.PackAsAnalyzer](https://github.com/ViktorHofer/PackAsAnalyzer).

This is used in three parts, and [SDK Reference](https://github.com/hwoodiwiss/ArgumentativeFilters/blob/main/Directory.Build.props#L2), and then some adjustments to the [ProjectReference](https://github.com/hwoodiwiss/ArgumentativeFilters/blob/main/src/ArgumentativeFilters/ArgumentativeFilters.csproj#L12) where the attributes project is referencing the generator project, then the `<None>` item specifying to output to `analyzers/dotnet/cs` goes in the Generator project.

**Comment by neil-gilbert** [comment]
Thanks @hwoodiwiss i followed how you had setup your Minimal Api source generator project (which is really nice!) and applied here - Thanks for the suggestions
